pollingInterval: 120
watchers:
  - path: "/Users/cian.gallagher/input"
    destination: "/Users/cian.gallagher/output"
    ext: ".txt"
  - path: "/Users/cian.gallagher/input"
    destination: "/Users/cian.gallagher/output"
    ext: ".mp4"
