pollingInterval: 10
watchers:
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Documents"
    ext: ".txt"
    pattern: "(?i)(financial-report-[a-z]+-[0-9]+.txt)"
  - path: "/home/cian/Downloads"
    destination: "/home/cian/Videos"
    ext: ".mp4"
