name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
    - "cmd/**"
    - "event/**"
    - "utils/**"
    - "watcher/**"
    - "go.*"
    - ".github/workflows/test.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: '~1.23'
    - name: Install Dependencies
      run: |
        go install github.com/rakyll/gotest@latest
        go install golang.org/x/lint/golint@latest
    - name: Lint
      run: |
        make lint-all
    - name: Format
      run: |
        make test-format-all
    - name: Test
      run: |
        make test-all
